---
version: "3.6"

services:
  server:
    healthcheck:
      test:
        [
          "CMD",
          "grpc_health_probe",
          "-addr",
          "localhost:${DOCKER_PORT_GRPC}"
        ]
      interval: 5s
      timeout: 5s
      retries: 3
      start_period: 30s
    volumes:
      - type: bind
        source: logs/
        target: /logs/
    configs:
      - source: log4rs
        target: ${LOG_CONFIG}
      - source: dot-env
        target: /.env
    environment:
      - DOCKER_PORT_REST
      - DOCKER_PORT_GRPC
      - LOG_CONFIG
      - REDIS__URL
      - REDIS__POOL__MAX_SIZE
      - REDIS__POOL__TIMEOUTS__WAIT__SECS
      - REDIS__POOL__TIMEOUTS__WAIT__NANOS
      - AMQP__URL
      - AMQP__POOL__MAX_SIZE
      - AMQP__POOL__TIMEOUTS__WAIT__SECS
      - AMQP__POOL__TIMEOUTS__WAIT__NANOS
      - ASSETS_PORT_GRPC=$DOCKER_PORT_GRPC
      - ASSETS_PORT_REST
      - ASSETS_HOST_GRPC
      - ATC_PORT_GRPC=$DOCKER_PORT_GRPC
      - ATC_PORT_REST
      - ATC_HOST_GRPC
      - CARGO_PORT_GRPC=$DOCKER_PORT_GRPC
      - CARGO_PORT_REST
      - CARGO_HOST_GRPC
      - COMPLIANCE_PORT_GRPC=$DOCKER_PORT_GRPC
      - COMPLIANCE_PORT_REST
      - COMPLIANCE_HOST_GRPC
      - GIS_PORT_GRPC=$DOCKER_PORT_GRPC
      - GIS_HOST_GRPC
      - PRICING_PORT_GRPC=$DOCKER_PORT_GRPC
      - PRICING_HOST_GRPC
      - SCHEDULER_PORT_GRPC=$DOCKER_PORT_GRPC
      - SCHEDULER_HOST_GRPC
      - STORAGE_PORT_GRPC=$DOCKER_PORT_GRPC
      - STORAGE_HOST_GRPC
      - TELEMETRY_PORT_GRPC=$DOCKER_PORT_GRPC
      - TELEMETRY_PORT_REST
      - TELEMETRY_HOST_GRPC
      - DISCOVERY_PORT_GRPC=$DOCKER_PORT_GRPC
      - DISCOVERY_PORT_REST
      - DISCOVERY_HOST_GRPC
      - CONTACT_PORT_GRPC=$DOCKER_PORT_GRPC
      - CONTACT_PORT_REST
      - CONTACT_HOST_GRPC
      - REST_CONCURRENCY_LIMIT_PER_SERVICE
      - REST_CORS_ALLOWED_ORIGIN
      - REST_REQUEST_LIMIT_PER_SECOND
