---
version: '3.6'
volumes:
  redis-data:

services:
  server:
    container_name: arrow-redis
    image: redis:6.2-alpine
    restart: always
    expose:
      - ${REDIS_PORT}
    command: redis-server --save 20 1 --loglevel warning --port ${REDIS_PORT}
    healthcheck:
      test: ["CMD", "redis-cli","ping"]
      interval: 2s
      timeout: 1s
      retries: 3
    volumes:
      - redis-data:/data
    environment:
      - REDIS_DISABLE_COMMANDS=FLUSHDB,FLUSHALL,CONFIG
      - ALLOW_EMPTY_PASSWORD=yes
      - REDIS_PORT_NUMBER=${REDIS_PORT}
