---
version: '3.6'
volumes:
  cockroachdb:
  cockroachdb-ssl:

services:
  server:
    container_name: arrow-svc-storage
    image: ${STORAGE_IMAGE}:${STORAGE_TAG}
    volumes:
      - type: volume
        source: cockroachdb-ssl
        target: /cockroach/ssl
        read_only: true
    ports:
      - ${STORAGE_PORT_GRPC}:${STORAGE_PORT_GRPC}
    healthcheck:
      test: ["CMD", "grpc_health_probe", "-addr", "localhost:${STORAGE_PORT_GRPC}"]
      interval: 2s
      timeout: 1s
      retries: 3
    command: ${STORAGE_SERVER_ARGS}
    environment:
      - DOCKER_PORT_GRPC=${STORAGE_PORT_GRPC}
      - PG__USER
      - PG__DBNAME
      - PG__HOST
      - PG__PORT
      - PG__SSLMODE
      - DB_CA_CERT
      - DB_CLIENT_CERT
      - DB_CLIENT_KEY
