---
version: '3.6'
volumes:
  cockroachdb:
  cockroachdb-ssl:
  redis-data:

services:
  cockroachdb-init:
    extends:
      file: docker-compose/cockroachdb/svc.yml
      service: init

  cockroachdb:
    extends:
      file: docker-compose/cockroachdb/svc.yml
      service: server
    depends_on:
      cockroachdb-init:
        condition: service_completed_successfully

  redis:
    extends:
      file: docker-compose/redis/svc.yml
      service: server

  rabbitmq:
    extends:
      file: docker-compose/rabbitmq/svc.yml
      service: server

  svc-storage:
    extends:
      file: docker-compose/storage/svc.yml
      service: server
    depends_on:
      cockroachdb:
        condition: service_healthy

  svc-compliance:
    extends:
      file: docker-compose/compliance/svc.yml
      service: server

  svc-scheduler:
    extends:
      file: docker-compose/scheduler/svc.yml
      service: server
    depends_on:
      svc-storage:
        condition: service_healthy
      svc-compliance:
        condition: service_healthy

  svc-pricing:
    extends:
      file: docker-compose/pricing/svc.yml
      service: server

  svc-cargo:
    extends:
      file: docker-compose/cargo/svc.yml
      service: server
    depends_on:
      svc-storage:
        condition: service_healthy
      svc-scheduler:
        condition: service_healthy
      svc-pricing:
        condition: service_healthy

  svc-assets:
    extends:
      file: docker-compose/assets/svc.yml
      service: server
    depends_on:
      svc-storage:
        condition: service_healthy

  svc-telemetry:
    extends:
      file: docker-compose/telemetry/svc.yml
      service: server
    depends_on:
      svc-storage:
        condition: service_healthy
      redis:
        condition: service_healthy
      rabbitmq:
        condition: service_healthy

